version: '3.8'

services:
  node-service:
    build:
      context: ./api
    env_file:
      - ./webapp.env
    volumes:
      - ./api:/app
    depends_on:
      - db
  db:
    build:
      context: ./db
    image: mariadb:latest
    container_name: my-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: mydatabase
      MARIADB_USER: myuser
      MARIADB_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - my_db_data:/var/lib/mysql
  nginx:
    build:
      context: ./nginx  
    container_name: my-nginx
    ports:
      - "8080:8080" 
    depends_on:
      - node-service
volumes:
  my_db_data:
